'use client';
// import './globals.css';
import '../styles/globals.css';

import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/footer/footer';
import { useIsMobile } from '@/hooks/useIsMobile';
import MobileNav from '@/components/MobileNav/MobileNav';
import MobileNavMenu from '@/components/MobileNavMenu/MobileNavMenu';
import FooterMobile from '@/components/FooterMobile/FooterMobile';
import { useState } from 'react';
import SideBar from '@/components/SideBar/SideBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, setIsShow, isShow }) {
	const [isMobileNav, setIsMobileNav] = useState(false);
	const isMobile = useIsMobile();

	return (
		<>
			<html lang='en'>
				<body className={inter.className}>
					{isMobileNav && (
						<MobileNavMenu
							setIsShow={setIsShow}
							setIsMobileNav={setIsMobileNav}
							isMobileNav={isMobileNav}
						/>
					)}


					{isMobile ? (
						<MobileNav
							setIsMobileNav={setIsMobileNav}
							isMobileNav={isMobileNav}
						/>
					) : (
						<Navbar
							setIsShow={setIsShow}
							isShow={isShow}
							setIsMobileNav={setIsMobileNav}
						/>
					)}

					<div>{children}</div>
					{isMobile && <FooterMobile />}
					{!isMobile && <Footer />}
				</body>
			</html>
		</>
	);
}
